version: "3.8"

services:
  k6:
    image: loadimpact/k6
    platform: linux/amd64
    entrypoint: ["k6", "run", "/scripts/test-script.js"]
    volumes:
      - ./scripts:/scripts
    environment:
      - K6_INFLUXDB_PUSH_INTERVAL=1s
      - K6_INFLUXDB_ADDR=http://influxdb:8086/k6
    networks:
      - monitoring_net

  influxdb:
    image: influxdb:1.8-alpine
    platform: linux/amd64
    container_name: influxdb
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_BIND_ADDRESS=:8086
    volumes:
      - /Users/ubs/nyn/influxdb-data:/var/lib/influxdb
    ports:
      - "8086:8086"
    networks:
      - monitoring_net

  grafana:
    image: grafana/grafana
    platform: linux/amd64
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # 기본 로그인 정보 설정
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring_net

networks:
  monitoring_net:
    driver: bridge

volumes:
  influxdb-data:
  grafana-data:
